import { HeroDef, Position } from './types';

// ── Hero Definitions ──────────────────────────────────────────────
export const HEROES: HeroDef[] = [
  {
    id: 'zhao_yun',
    name: 'Zhao Yun',
    class: 'warrior',
    icon: '⚔️',
    title: 'Dragon Spear',
    description: 'A balanced warrior who excels at diving into fights with his dash abilities.',
    baseStats: {
      maxHp: 600,
      maxMana: 300,
      attack: 55,
      defense: 30,
      attackRange: 60,
      attackSpeed: 1.0,
      moveSpeed: 3.5,
      hpRegen: 3,
      manaRegen: 2,
    },
    growthPerLevel: { maxHp: 80, maxMana: 30, attack: 8, defense: 5 },
    abilities: [
      {
        id: 'dash',
        name: 'Dragon Dash',
        icon: '💨',
        manaCost: 40,
        cooldown: 6,
        range: 200,
        damage: 80,
        description: 'Dash forward dealing damage to enemies in path.',
      },
      {
        id: 'sweep',
        name: 'Spear Sweep',
        icon: '🌀',
        manaCost: 50,
        cooldown: 8,
        range: 100,
        damage: 120,
        effectRadius: 100,
        description: 'Sweep spear in a circle damaging all nearby enemies.',
      },
      {
        id: 'dragon_strike',
        name: 'Dragon Strike',
        icon: '🐉',
        manaCost: 80,
        cooldown: 30,
        range: 150,
        damage: 250,
        effectRadius: 120,
        description: 'Ultimate: Unleash a devastating dragon strike dealing massive area damage.',
      },
    ],
  },
  {
    id: 'zhou_yu',
    name: 'Zhou Yu',
    class: 'mage',
    icon: '🔥',
    title: 'Fire Strategist',
    description: 'A powerful mage who rains fire upon enemies from a safe distance.',
    baseStats: {
      maxHp: 420,
      maxMana: 450,
      attack: 40,
      defense: 18,
      attackRange: 180,
      attackSpeed: 0.7,
      moveSpeed: 3.0,
      hpRegen: 2,
      manaRegen: 4,
    },
    growthPerLevel: { maxHp: 55, maxMana: 45, attack: 12, defense: 3 },
    abilities: [
      {
        id: 'fireball',
        name: 'Fireball',
        icon: '🔴',
        manaCost: 35,
        cooldown: 4,
        range: 250,
        damage: 100,
        description: 'Hurl a fireball at the nearest enemy.',
      },
      {
        id: 'flame_wall',
        name: 'Flame Wall',
        icon: '🧱',
        manaCost: 60,
        cooldown: 10,
        range: 200,
        damage: 80,
        effectRadius: 120,
        description: 'Create a wall of fire damaging all enemies in an area.',
      },
      {
        id: 'inferno',
        name: 'Inferno',
        icon: '☄️',
        manaCost: 100,
        cooldown: 35,
        range: 300,
        damage: 350,
        effectRadius: 150,
        description: 'Ultimate: Rain fire from the sky dealing devastating damage in a large area.',
      },
    ],
  },
  {
    id: 'hou_yi',
    name: 'Hou Yi',
    class: 'archer',
    icon: '🏹',
    title: 'Sun Piercer',
    description: 'A ranged marksman who picks off enemies from afar with precise arrows.',
    baseStats: {
      maxHp: 380,
      maxMana: 280,
      attack: 65,
      defense: 15,
      attackRange: 220,
      attackSpeed: 1.2,
      moveSpeed: 3.2,
      hpRegen: 2,
      manaRegen: 2,
    },
    growthPerLevel: { maxHp: 50, maxMana: 25, attack: 14, defense: 2 },
    abilities: [
      {
        id: 'scatter_shot',
        name: 'Scatter Shot',
        icon: '🎯',
        manaCost: 30,
        cooldown: 5,
        range: 250,
        damage: 70,
        effectRadius: 80,
        description: 'Fire scattered arrows hitting multiple enemies.',
      },
      {
        id: 'arrow_rain',
        name: 'Arrow Rain',
        icon: '🌧️',
        manaCost: 55,
        cooldown: 10,
        range: 300,
        damage: 110,
        effectRadius: 130,
        description: 'Rain arrows down on an area.',
      },
      {
        id: 'sun_piercer',
        name: 'Sun Piercer',
        icon: '☀️',
        manaCost: 90,
        cooldown: 35,
        range: 400,
        damage: 300,
        description: 'Ultimate: Fire a piercing arrow that deals massive single-target damage.',
      },
    ],
  },
  {
    id: 'zhang_fei',
    name: 'Zhang Fei',
    class: 'tank',
    icon: '🛡️',
    title: 'Unbreakable',
    description: 'A mighty tank who absorbs damage and protects allies with his massive shield.',
    baseStats: {
      maxHp: 800,
      maxMana: 250,
      attack: 35,
      defense: 45,
      attackRange: 55,
      attackSpeed: 0.8,
      moveSpeed: 3.0,
      hpRegen: 5,
      manaRegen: 2,
    },
    growthPerLevel: { maxHp: 110, maxMana: 20, attack: 5, defense: 8 },
    abilities: [
      {
        id: 'shield_bash',
        name: 'Shield Bash',
        icon: '💥',
        manaCost: 35,
        cooldown: 6,
        range: 80,
        damage: 60,
        description: 'Bash nearby enemies with your shield.',
      },
      {
        id: 'war_cry',
        name: 'War Cry',
        icon: '📣',
        manaCost: 50,
        cooldown: 12,
        range: 150,
        damage: 40,
        effectRadius: 150,
        healAmount: 100,
        description: 'Let out a war cry, damaging enemies and healing allies nearby.',
      },
      {
        id: 'unbreakable',
        name: 'Unbreakable',
        icon: '🏔️',
        manaCost: 80,
        cooldown: 40,
        range: 0,
        damage: 0,
        healAmount: 400,
        effectRadius: 200,
        description: 'Ultimate: Become unbreakable, restoring HP and boosting nearby allies.',
      },
    ],
  },
  {
    id: 'li_bai',
    name: 'Li Bai',
    class: 'assassin',
    icon: '🗡️',
    title: 'Sword Saint',
    description: 'A lightning-fast assassin who strikes from the shadows with deadly precision.',
    baseStats: {
      maxHp: 450,
      maxMana: 320,
      attack: 70,
      defense: 20,
      attackRange: 55,
      attackSpeed: 1.3,
      moveSpeed: 4.0,
      hpRegen: 2,
      manaRegen: 3,
    },
    growthPerLevel: { maxHp: 60, maxMana: 30, attack: 15, defense: 3 },
    abilities: [
      {
        id: 'shadow_step',
        name: 'Shadow Step',
        icon: '👤',
        manaCost: 35,
        cooldown: 5,
        range: 180,
        damage: 90,
        description: 'Teleport behind the nearest enemy and strike.',
      },
      {
        id: 'blade_dance',
        name: 'Blade Dance',
        icon: '💃',
        manaCost: 50,
        cooldown: 8,
        range: 100,
        damage: 140,
        effectRadius: 90,
        description: 'Perform a deadly blade dance hitting all nearby enemies.',
      },
      {
        id: 'sword_saint',
        name: 'Sword Saint',
        icon: '⚡',
        manaCost: 90,
        cooldown: 30,
        range: 120,
        damage: 400,
        description: 'Ultimate: Become one with the sword, dealing devastating single-target damage.',
      },
    ],
  },
  {
    id: 'bian_que',
    name: 'Bian Que',
    class: 'support',
    icon: '💚',
    title: 'Divine Healer',
    description: 'A healer who sustains allies and weakens enemies with ancient medicine.',
    baseStats: {
      maxHp: 480,
      maxMana: 400,
      attack: 30,
      defense: 22,
      attackRange: 160,
      attackSpeed: 0.8,
      moveSpeed: 3.2,
      hpRegen: 3,
      manaRegen: 5,
    },
    growthPerLevel: { maxHp: 60, maxMana: 40, attack: 6, defense: 4 },
    abilities: [
      {
        id: 'heal',
        name: 'Healing Light',
        icon: '✨',
        manaCost: 40,
        cooldown: 6,
        range: 200,
        damage: 0,
        healAmount: 120,
        effectRadius: 120,
        description: 'Heal yourself and nearby allies.',
      },
      {
        id: 'poison',
        name: 'Toxic Dart',
        icon: '☠️',
        manaCost: 35,
        cooldown: 5,
        range: 200,
        damage: 90,
        description: 'Fire a toxic dart at the nearest enemy.',
      },
      {
        id: 'resurrection',
        name: 'Resurrection',
        icon: '🌟',
        manaCost: 120,
        cooldown: 60,
        range: 0,
        damage: 0,
        healAmount: 500,
        effectRadius: 200,
        description: 'Ultimate: Fully restore HP and heal all nearby allies massively.',
      },
    ],
  },
];

// ── Map Configuration ──────────────────────────────────────────────
export const MAP = {
  width: 3000,
  height: 900,
  laneY: 450,
  // Background color zones
  groundColor: '#1a2332',
  laneColor: '#2a3a4a',
  grassColor: '#1a3020',
};

// ── Structure Positions ──────────────────────────────────────────
export const BLUE_BASE: Position = { x: 120, y: 450 };
export const RED_BASE: Position = { x: 2880, y: 450 };

export const BLUE_TURRETS: Position[] = [
  { x: 450, y: 450 },   // Outer turret
  { x: 800, y: 450 },   // Inner turret
];

export const RED_TURRETS: Position[] = [
  { x: 2550, y: 450 },  // Outer turret
  { x: 2200, y: 450 },  // Inner turret
];

// ── Spawn Positions ──────────────────────────────────────────────
export const BLUE_SPAWNS: Position[] = [
  { x: 200, y: 350 },
  { x: 200, y: 450 },
  { x: 200, y: 550 },
];

export const RED_SPAWNS: Position[] = [
  { x: 2800, y: 350 },
  { x: 2800, y: 450 },
  { x: 2800, y: 550 },
];

// ── Game Constants ──────────────────────────────────────────────
export const GAME = {
  TICK_RATE: 33, // ~30fps
  VIEWPORT_WIDTH: 600,
  VIEWPORT_HEIGHT: 400,
  MINION_SPAWN_INTERVAL: 25, // seconds
  MINION_WAVE_SIZE: 3,
  MINION_HP: 150,
  MINION_ATTACK: 15,
  MINION_DEFENSE: 5,
  MINION_SPEED: 2.0,
  MINION_RANGE: 50,
  MINION_SIZE: 14,
  TURRET_HP: 1200,
  TURRET_ATTACK: 80,
  TURRET_DEFENSE: 40,
  TURRET_RANGE: 200,
  TURRET_SPEED: 0.8,
  TURRET_SIZE: 30,
  BASE_HP: 2500,
  BASE_ATTACK: 60,
  BASE_DEFENSE: 50,
  BASE_RANGE: 180,
  BASE_SIZE: 45,
  XP_PER_MINION: 30,
  XP_PER_HERO_KILL: 150,
  GOLD_PER_MINION: 20,
  GOLD_PER_HERO_KILL: 300,
  GOLD_PER_TURRET: 150,
  RESPAWN_TIME_BASE: 5,
  RESPAWN_TIME_PER_LEVEL: 1,
  MAX_LEVEL: 15,
  XP_BASE: 100,
  XP_SCALE: 60,
  HERO_SIZE: 22,
  PROJECTILE_SPEED: 8,
  KILL_FEED_DURATION: 5,
  AI_DECISION_INTERVAL: 0.5, // seconds between AI decisions
};

// ── Colors ──────────────────────────────────────────────────────
export const GAME_COLORS = {
  blue: {
    primary: '#4488ff',
    light: '#6699ff',
    dark: '#2266cc',
    hp: '#44aaff',
  },
  red: {
    primary: '#ff4444',
    light: '#ff6666',
    dark: '#cc2222',
    hp: '#ff4444',
  },
  turret: {
    blue: '#5599dd',
    red: '#dd5555',
  },
  base: {
    blue: '#3377cc',
    red: '#cc3333',
  },
  minion: {
    blue: '#66aaee',
    red: '#ee6666',
  },
  hp: {
    high: '#44dd44',
    mid: '#ddaa22',
    low: '#dd4444',
  },
  mana: '#4488ff',
  xp: '#ddaa22',
  gold: '#ffcc00',
  map: {
    ground: '#1a2332',
    lane: '#2a3a4a',
    grass: '#1a3020',
    grid: '#222d3a',
  },
  ui: {
    bg: '#0a0e14',
    panel: '#151c28',
    border: '#2a3a4a',
    text: '#ddeeff',
    textDim: '#667788',
  },
};

// ── Helper to get XP needed for a level ──
export function xpForLevel(level: number): number {
  return GAME.XP_BASE + (level - 1) * GAME.XP_SCALE;
}
